FROM python:3.13-slim

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        gnupg \
        gcc \
        g++ \
        build-essential \
        python3-dev \
        # these 3 for configuration of kafka, so you don't have issues
        libssl-dev \
        libsasl2-dev \
        pkg-config \
        && rm -rf /var/lib/apt/lists/*

# Manually install librdkafka with sasl/ssl support
RUN curl -fsSl https://github.com/confluentinc/librdkafka/archive/refs/tags/v.2.8.0.tar.gz -o liberdkafka.tar.gz && \
    tar -xzf librdkafka.tar.gz && \
    cd librdkafka-2.8.0 && \
    ./configure --enable-sasl --enable-ssl && \
    make && \
    make install && \
    ldconfig && \
    cd .. && \
    rm -rf librdkafka-2.8.0 librdkafka.tar.gz

# Copy requirements file and install dependencies
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy the application code
COPY . .

# ENTRYPOINT to run the producer
ENTRYPOINT ["python3", "main.py"]